import re
from typing import List


# group similar words under one cleaner skill name
SKILL_NORMALIZATION_MAP = {
    "analysis": "data analysis",
    "analytical": "data analysis",
    "analytical skills": "data analysis",
    "analytics": "data analysis",
    "data analytics": "data analysis",
    "data analysis": "data analysis",
    "data analyst": "data analysis",
    "data analyst skills": "data analysis",
    "reporting": "data analysis",
    "business reporting": "data analysis",
    "insights": "data analysis",
    "data insights": "data analysis",
    "trend analysis": "data analysis",
    "forecasting": "data analysis",
    "data interpretation": "data analysis",
    "data processing": "data analysis",
    "visualisation": "data visualization",
    "visualization": "data visualization",
    "data visualization": "data visualization",
    "data visualisation": "data visualization",
    "visual analytics": "data visualization",
    "dashboards": "data visualization",
    "dashboard": "data visualization",
    "tableau": "data visualization",
    "power bi": "data visualization",
    "bi tools": "data visualization",
    "business intelligence": "data visualization",
    "excel charts": "data visualization",
    "python": "python",
    "python programming": "python",
    "python scripting": "python",
    "pandas": "python",
    "numpy": "python",
    "matplotlib": "python",
    "seaborn": "python",
    "jupyter": "python",
    "jupyter notebook": "python",
    "jupyter notebooks": "python",
    "sql": "sql",
    "mysql": "sql",
    "postgresql": "sql",
    "postgres": "sql",
    "sqlite": "sql",
    "sql server": "sql",
    "microsoft sql server": "sql",
    "tsql": "sql",
    "database queries": "sql",
    "querying": "sql",
    "database management": "sql",
    "database querying": "sql",
    "machine learning": "machine learning",
    "ml": "machine learning",
    "supervised learning": "machine learning",
    "unsupervised learning": "machine learning",
    "classification": "machine learning",
    "regression": "machine learning",
    "scikit-learn": "machine learning",
    "sklearn": "machine learning",
    "predictive modeling": "machine learning",
    "predictive modelling": "machine learning",
    "model training": "machine learning",
    "model evaluation": "machine learning",
    "feature engineering": "machine learning",
    "deep learning": "deep learning",
    "neural networks": "deep learning",
    "tensorflow": "deep learning",
    "keras": "deep learning",
    "pytorch": "deep learning",
    "cnn": "deep learning",
    "rnn": "deep learning",
    "nlp": "natural language processing",
    "natural language processing": "natural language processing",
    "text mining": "natural language processing",
    "text analysis": "natural language processing",
    "spacy": "natural language processing",
    "nltk": "natural language processing",
    "language models": "natural language processing",
    "text preprocessing": "natural language processing",
    "aws": "cloud computing",
    "azure": "cloud computing",
    "gcp": "cloud computing",
    "google cloud": "cloud computing",
    "cloud": "cloud computing",
    "cloud computing": "cloud computing",
    "cloud services": "cloud computing",
    "cloud platforms": "cloud computing",
    "cloud infrastructure": "cloud computing",
    "amazon web services": "cloud computing",
    "microsoft azure": "cloud computing",
    "docker": "devops",
    "kubernetes": "devops",
    "ci/cd": "devops",
    "cicd": "devops",
    "jenkins": "devops",
    "github actions": "devops",
    "devops": "devops",
    "deployment": "devops",
    "automation": "devops",
    "infrastructure automation": "devops",
    "containerization": "devops",
    "containerisation": "devops",
    "git": "version control",
    "github": "version control",
    "gitlab": "version control",
    "version control": "version control",
    "source control": "version control",
    "branching": "version control",
    "fastapi": "fastapi",
    "streamlit": "streamlit",
    "api": "api development",
    "apis": "api development",
    "rest api": "api development",
    "restful api": "api development",
    "api development": "api development",
    "api design": "api development",
    "api integration": "api development",
    "web services": "api development",
    "microservices": "api development",
    "marketing": "marketing",
    "digital marketing": "marketing",
    "product marketing": "marketing",
    "brand marketing": "marketing",
    "campaign management": "marketing",
    "campaign planning": "marketing",
    "market research": "marketing",
    "market analysis": "marketing",
    "seo": "marketing",
    "sem": "marketing",
    "social media": "social media management",
    "social media management": "social media management",
    "social media marketing": "social media management",
    "instagram": "social media management",
    "facebook": "social media management",
    "linkedin": "social media management",
    "tiktok": "social media management",
    "content writing": "content creation",
    "content creation": "content creation",
    "copywriting": "content creation",
    "blog writing": "content creation",
    "content strategy": "content creation",
    "graphic design": "graphic design",
    "canva": "graphic design",
    "adobe photoshop": "graphic design",
    "photoshop": "graphic design",
    "adobe illustrator": "graphic design",
    "illustrator": "graphic design",
    "backend": "backend development",
    "backend development": "backend development",
    "django": "backend development",
    "flask": "backend development",
    "node.js": "backend development",
    "nodejs": "backend development",
    "spring boot": "backend development",
    "server-side development": "backend development",
    "server side development": "backend development",
    "web backend": "backend development",
    "frontend": "frontend development",
    "frontend development": "frontend development",
    "react": "react",
    "react.js": "react",
    "javascript": "javascript",
    "js": "javascript",
    "typescript": "javascript",
    "frontend engineering": "frontend development",
    "user interfaces": "frontend development",
    "ui development": "frontend development",
    "html": "html/css",
    "css": "html/css",
    "bootstrap": "html/css",
    "tailwind": "html/css",
    "responsive design": "html/css",
    "web design": "html/css",
    "web styling": "html/css",
    "excel": "spreadsheet tools",
    "google sheets": "spreadsheet tools",
    "spreadsheet": "spreadsheet tools",
    "spreadsheets": "spreadsheet tools",
    "vlookup": "spreadsheet tools",
    "pivot table": "spreadsheet tools",
    "pivot tables": "spreadsheet tools",
    "xlookup": "spreadsheet tools",
    "formulas": "spreadsheet tools",
    "spreadsheet modelling": "spreadsheet tools",
    "spreadsheet modeling": "spreadsheet tools",
    "word": "office tools",
    "microsoft word": "office tools",
    "office 365": "office tools",
    "microsoft office": "office tools",
    "office tools": "office tools",
    "ms office": "office tools",
    "word processing": "office tools",
    "powerpoint": "presentation skills",
    "presentation": "presentation skills",
    "presentations": "presentation skills",
    "public speaking": "presentation skills",
    "presenting": "presentation skills",
    "requirements gathering": "business analysis",
    "business analysis": "business analysis",
    "stakeholder management": "business analysis",
    "stakeholder communication": "business analysis",
    "process mapping": "business analysis",
    "requirements analysis": "business analysis",
    "etl": "data engineering",
    "data pipelines": "data engineering",
    "data pipeline": "data engineering",
    "data warehousing": "data engineering",
    "data warehouse": "data engineering",
    "spark": "data engineering",
    "hadoop": "data engineering",
    "big data": "data engineering",
    "data integration": "data engineering",
    "communication": "communication",
    "communication skills": "communication",
    "written communication": "communication",
    "verbal communication": "communication",
    "interpersonal skills": "communication",
    "stakeholder communication": "communication",
    "client communication": "communication",
    "customer service": "customer service",
    "client service": "customer service",
    "customer support": "customer service",
    "customer care": "customer service",
    "client relations": "customer service",
    "guest service": "customer service",
    "phone etiquette": "customer service",
    "call handling": "customer service",
    "teamwork": "teamwork",
    "team player": "teamwork",
    "collaboration": "teamwork",
    "collaborative working": "teamwork",
    "cross-functional collaboration": "teamwork",
    "cross functional collaboration": "teamwork",
    "problem solving": "problem solving",
    "problem-solving": "problem solving",
    "critical thinking": "problem solving",
    "troubleshooting": "problem solving",
    "decision making": "problem solving",
    "solution focused": "problem solving",
    "leadership": "leadership",
    "mentoring": "leadership",
    "coaching": "leadership",
    "people management": "leadership",
    "sales": "sales",
    "selling": "sales",
    "sales strategy": "sales",
    "sales management": "sales",
    "business development": "sales",
    "lead generation": "sales",
    "negotiation": "sales",
    "closing sales": "sales",
    "retail sales": "sales",
    "account management": "sales",
    "project coordination": "project coordination",
    "project coordinator": "project coordination",
    "coordination": "project coordination",
    "organizing": "project coordination",
    "organisation": "project coordination",
    "project management": "project management",
    "agile": "project management",
    "scrum": "project management",
    "jira": "project management",
    "kanban": "project management",
    "planning": "project management",
    "task management": "project management",
    "scheduling": "scheduling",
    "calendar management": "scheduling",
    "appointment scheduling": "scheduling",
    "reservation": "scheduling",
    "reservations": "scheduling",
    "time management": "scheduling",
    "administration": "administration",
    "administrative": "administration",
    "administrative support": "administration",
    "administrative assistance": "administration",
    "office administration": "administration",
    "clerical work": "administration",
    "data entry": "administration",
    "filing": "administration",
    "office management": "office management",
    "front desk": "office management",
    "reception": "office management",
    "receptionist": "office management",
    "budgeting": "budgeting",
    "budget management": "budgeting",
    "cost control": "budgeting",
    "forecasting and budgeting": "budgeting",
    "accounting": "accounting",
    "bookkeeping": "accounting",
    "financial reporting": "accounting",
    "accounts payable": "accounting",
    "accounts receivable": "accounting",
    "general ledger": "accounting",
    "reconciliation": "accounting",
    "auditing": "accounting",
    "finance": "finance",
    "financial analysis": "finance",
    "fp&a": "finance",
    "financial planning": "finance",
    "financial modelling": "finance",
    "financial modeling": "finance",
    "loan processing": "finance",
    "mortgage": "finance",
    "banking": "finance",
    "legal": "legal support",
    "legal research": "legal support",
    "legal writing": "legal support",
    "legal documentation": "legal support",
    "litigation": "legal support",
    "contract review": "legal support",
    "contract drafting": "legal support",
    "case management": "legal support",
    "estate planning": "legal support",
    "trusts and estates": "legal support",
    "personal injury": "legal support",
    "compliance": "compliance",
    "regulatory compliance": "compliance",
    "quality assurance": "quality assurance",
    "quality control": "quality assurance",
    "validation": "quality assurance",
    "documentation": "documentation",
    "record keeping": "documentation",
    "report writing": "documentation",
    "training": "training and development",
    "staff training": "training and development",
    "employee training": "training and development",
    "learning and development": "training and development",
    "instruction": "training and development",
    "teaching": "training and development",
    "coaching clients": "training and development",
    "healthcare": "healthcare support",
    "patient care": "healthcare support",
    "clinical care": "healthcare support",
    "medical terminology": "healthcare support",
    "electronic health records": "healthcare support",
    "ehr": "healthcare support",
    "therapy": "therapy and counseling",
    "therapeutic support": "therapy and counseling",
    "counseling": "therapy and counseling",
    "counselling": "therapy and counseling",
    "mental health": "therapy and counseling",
    "behavior analysis": "therapy and counseling",
    "behaviour analysis": "therapy and counseling",
    "nursing": "nursing",
    "registered nurse": "nursing",
    "rn": "nursing",
    "respiratory therapy": "respiratory therapy",
    "respiratory therapist": "respiratory therapy",
    "dental hygiene": "dental care",
    "dental hygienist": "dental care",
    "dentistry": "dental care",
    "hospitality": "hospitality",
    "restaurant": "hospitality",
    "food service": "hospitality",
    "guest experience": "hospitality",
    "housekeeping": "hospitality",
    "food safety": "food safety",
    "kitchen operations": "food safety",
    "inventory": "inventory management",
    "inventory control": "inventory management",
    "stock management": "inventory management",
    "supply management": "inventory management",
    "procurement": "inventory management",
    "operations": "operations management",
    "operations management": "operations management",
    "process improvement": "operations management",
    "workflow management": "operations management",
    "logistics": "operations management",
    "maintenance": "maintenance",
    "preventive maintenance": "maintenance",
    "equipment maintenance": "maintenance",
    "troubleshooting equipment": "maintenance",
    "hvac": "hvac",
    "heating ventilation and air conditioning": "hvac",
    "mechanical systems": "hvac",
    "plumbing": "plumbing",
    "pipe fitting": "plumbing",
    "sheet metal": "sheet metal work",
    "fabrication": "sheet metal work",
    "welding": "sheet metal work",
    "construction": "construction",
    "construction management": "construction",
    "site inspection": "construction",
    "building systems": "construction",
    "safety procedures": "construction",
    "architecture": "architecture",
    "architect": "architecture",
    "architectural design": "architecture",
    "structural engineering": "engineering",
    "engineering": "engineering",
    "civil engineering": "engineering",
    "mechanical engineering": "engineering",
    "cad": "cad design",
    "autocad": "cad design",
    "cad/cam": "cad design",
    "design drafting": "cad design",
    "admissions": "admissions and outreach",
    "student recruitment": "admissions and outreach",
    "outreach": "admissions and outreach",
    "fundraising": "fundraising",
    "donor relations": "fundraising",
    "event planning": "event coordination",
    "event coordination": "event coordination",
    "event management": "event coordination",
    "community engagement": "community engagement",
    "public relations": "community engagement",
    "worship": "music leadership",
    "music": "music leadership",
    "music ministry": "music leadership",
}


# use the normalized skill names as the main output list
KNOWN_SKILLS = sorted(set(SKILL_NORMALIZATION_MAP.values()))


def normalize_skill_name(skill: str) -> str:
    # convert any raw skill text into one normalized skill label
    lowered_skill = (skill or "").strip().lower()
    return SKILL_NORMALIZATION_MAP.get(lowered_skill, lowered_skill)


def normalize_skill_list(skills: List[str]) -> List[str]:
    # normalize skills, remove duplicates, and sort them
    normalized_skills = set()

    for skill in skills:
        normalized_skill = normalize_skill_name(skill)
        if normalized_skill:
            normalized_skills.add(normalized_skill)

    return sorted(normalized_skills)


def extract_skills_from_text(text: str) -> List[str]:
    # make the text lowercase so matching is easier
    lowered_text = (text or "").lower()
    found_skills = set()

    # check if each known word or phrase appears as a real term
    for raw_skill, normalized_skill in sorted(
        SKILL_NORMALIZATION_MAP.items(),
        key=lambda item: len(item[0]),
        reverse=True,
    ):
        skill_pattern = r"(?<!\w)" + re.escape(raw_skill) + r"(?!\w)"
        if re.search(skill_pattern, lowered_text):
            found_skills.add(normalized_skill)

    # also keep direct canonical skill matches for multi-word skills
    for skill in KNOWN_SKILLS:
        skill_pattern = r"(?<!\w)" + re.escape(skill) + r"(?!\w)"
        if re.search(skill_pattern, lowered_text):
            found_skills.add(skill)

    return normalize_skill_list(list(found_skills))


def compare_normalized_skills(cv_skills: List[str], job_skills: List[str]):
    # compare normalized cv and job skills in one shared place
    normalized_cv_skills = normalize_skill_list(cv_skills)
    normalized_job_skills = normalize_skill_list(job_skills)
    normalized_cv_set = set(normalized_cv_skills)
    matching_skills = sorted(skill for skill in normalized_job_skills if skill in normalized_cv_set)
    missing_skills = sorted(skill for skill in normalized_job_skills if skill not in normalized_cv_set)

    return {
        "matching_skills": matching_skills,
        "missing_skills": missing_skills,
        "normalized_cv_skills": normalized_cv_skills,
        "normalized_job_skills": normalized_job_skills,
    }


def compare_skills(cv_skills: List[str], job_skills: List[str]) -> List[str]:
    # keep the old helper name for simple missing-skill lookups
    return compare_normalized_skills(cv_skills, job_skills)["missing_skills"]
